<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>HolyHand.Platform</RootNamespace>
    <AssemblyName>HolyHand.Platform</AssemblyName>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HolyHand.Core\HolyHand.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Windows.CsWin32">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="FlaUI.UIA3" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\NativeMethods.txt" Link="NativeMethods.txt" />
  </ItemGroup>

</Project>
